[project]
name = "FastSAM"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch==2.7.1",
    "onnx>=1.19.0",
    "onnxruntime>=1.20.1",
    "ultralytics>=8.4.126",
    "onnxslim==0.1.96",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"
